# Generated by Django 2.0.2 on 2018-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.TextField(blank=True),
        ),
    ]
