# Generated by Django 2.0.2 on 2018-02-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paginghelper',
        ),
    ]
