# Generated by Django 2.0.2 on 2018-02-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0006_auto_20180203_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drama2',
            old_name='field8',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='drama2',
            old_name='field5',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='drama2',
            old_name='field7',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='drama2',
            old_name='field9',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='drama2',
            old_name='field6',
            new_name='title',
        ),
    ]
