# Generated by Django 2.0.1 on 2018-02-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('write_by', models.CharField(max_length=20, verbose_name='글쓴이')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
