# Generated by Django 2.0.1 on 2018-01-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30, verbose_name='장소')),
                ('open_Date', models.DateTimeField()),
                ('end_Date', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_genre', models.CharField(max_length=10, verbose_name='장르')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='사이트이름')),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
        ),
        migrations.CreateModel(
            name='Seat_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_seat_photo', models.ImageField(upload_to='')),
                ('sub_seat_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='drama',
            name='genre',
            field=models.ManyToManyField(to='yeonsonam.Genre'),
        ),
        migrations.AddField(
            model_name='drama',
            name='price',
            field=models.ManyToManyField(to='yeonsonam.Price'),
        ),
        migrations.AddField(
            model_name='drama',
            name='seat_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Seat_photo'),
        ),
    ]
