# Generated by Django 2.0.1 on 2018-02-10 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drama2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True)),
                ('genre', models.CharField(blank=True, max_length=150, null=True)),
                ('key', models.CharField(blank=True, max_length=150, null=True)),
                ('openrun', models.CharField(blank=True, max_length=150, null=True)),
                ('poster', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('start', models.CharField(blank=True, max_length=150, null=True)),
                ('end', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=300, null=True)),
                ('place_id', models.CharField(blank=True, max_length=300, null=True)),
                ('cast', models.CharField(blank=True, max_length=300, null=True)),
                ('crew', models.CharField(blank=True, max_length=300, null=True)),
                ('runtime', models.CharField(blank=True, max_length=300, null=True)),
                ('age', models.CharField(blank=True, max_length=300, null=True)),
                ('enterprise', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('styurl', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=300, null=True)),
                ('liker_set', models.ManyToManyField(related_name='liked_drama2_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Drama2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='drama2',
            name='tag',
            field=models.ManyToManyField(blank=True, to='yeonsonam.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Drama2'),
        ),
    ]
