# Generated by Django 2.0.2 on 2018-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama222',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, null=True)),
                ('field2', models.TextField(blank=True, null=True)),
                ('field3', models.TextField(blank=True, null=True)),
                ('field4', models.TextField(blank=True, null=True)),
                ('field5', models.TextField(blank=True, null=True)),
                ('field6', models.TextField(blank=True, null=True)),
                ('field7', models.TextField(blank=True, null=True)),
                ('field8', models.TextField(blank=True, null=True)),
                ('field9', models.TextField(blank=True, null=True)),
                ('field10', models.TextField(blank=True, null=True)),
                ('field11', models.TextField(blank=True, null=True)),
                ('field12', models.TextField(blank=True, null=True)),
                ('field13', models.TextField(blank=True, null=True)),
                ('field14', models.TextField(blank=True, null=True)),
                ('field15', models.IntegerField(blank=True, null=True)),
                ('field16', models.TextField(blank=True, null=True)),
                ('field18', models.TextField(blank=True, null=True)),
                ('field19', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Drama222',
                'managed': False,
            },
        ),
    ]
