# Generated by Django 2.0.2 on 2018-02-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drama2',
            options={'managed': True},
        ),
    ]
