# Generated by Django 2.0.1 on 2018-01-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_of_discount', models.IntegerField(verbose_name='할인율')),
                ('name_of_discount', models.CharField(max_length=20, verbose_name='할인명')),
            ],
        ),
        migrations.CreateModel(
            name='Site_reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20)),
                ('site_url', models.URLField()),
                ('site_location', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='site_name',
        ),
        migrations.AddField(
            model_name='price',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Site_reservation'),
            preserve_default=False,
        ),
    ]
