# Generated by Django 2.0.1 on 2018-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0002_auto_20180130_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_reservation',
            name='site_location',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
