# Generated by Django 2.0.2 on 2018-02-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0002_auto_20180203_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama2',
            name='field2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field9',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='field_dbs',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
