# Generated by Django 2.0.2 on 2018-02-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0002_tag2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drama2',
            table='Drama2',
        ),
    ]
