# Generated by Django 2.0.2 on 2018-02-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0003_auto_20180203_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Discount'),
        ),
    ]
