# Generated by Django 2.0.1 on 2018-01-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0003_auto_20180130_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='name_of_discount',
            field=models.CharField(blank=True, max_length=20, verbose_name='할인명'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='rate_of_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='할인율'),
        ),
    ]
