# Generated by Django 2.0.1 on 2018-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0004_auto_20180130_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='title',
            field=models.CharField(default=None, max_length=30, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
