# Generated by Django 2.0.2 on 2018-02-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0005_auto_20180203_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drama2',
            old_name='field4',
            new_name='openrun',
        ),
    ]
