# Generated by Django 2.0.1 on 2018-01-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0005_drama_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='yeonsonam.Place')),
            ],
        ),
        migrations.AlterField(
            model_name='drama',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Place'),
        ),
    ]
