# Generated by Django 2.0.2 on 2018-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0006_kopis1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='Actor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='end_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='genre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='open_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='running_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
