# Generated by Django 2.0.1 on 2018-01-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0006_auto_20180130_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='배우이름')),
                ('actor_photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_num', models.CharField(max_length=10, verbose_name='회차')),
                ('sequence_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='drama',
            name='running_time',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drama',
            name='end_Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='open_Date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='drama',
            name='Actor',
            field=models.ManyToManyField(to='yeonsonam.Actor'),
        ),
        migrations.AddField(
            model_name='drama',
            name='sequence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yeonsonam.Sequence'),
            preserve_default=False,
        ),
    ]
