# Generated by Django 2.0.2 on 2018-02-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0007_auto_20180203_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama2',
            name='detail_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='drama2',
            name='poster',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
