# Generated by Django 2.0.2 on 2018-02-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0008_auto_20180203_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama2',
            name='age',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='cast',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='crew',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='enterprise',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='runtime',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='styurl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama2',
            name='time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
