# Generated by Django 2.0.2 on 2018-02-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0009_auto_20180204_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama2',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
