# Generated by Django 2.0.2 on 2018-02-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeonsonam', '0010_auto_20180204_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama2',
            name='start',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
